# Generated by Django 5.2.17 on 2026-09-28 02:36

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pedido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('folio', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('descripcion', models.CharField(max_length=200)),
                ('estado', models.CharField(default='Pendiente', max_length=50)),
                ('eta', models.CharField(default='En 30 minutos', max_length=50)),
            ],
        ),
    ]
