# Generated by Django 6.1.1 on 2026-09-28 05:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entregas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedido',
            name='medio_asignado',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='pedido',
            name='motivo_asignacion',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
